Custom markup via Options parameter
djkramnik/splitText pull request #2
Opened 2020-04-21 14:30 UTC by hansds

I was glad I could use this package in a project of mine, but needed functionality where two divs surrounded the line text. The effect I was aiming for can be seen in the title text here: https://www.beangels.eu/

I added a flexible solution where you could inject the necessary markup, see README.

2020-04-23 04:05 UTC, djkramnik requested changes
Thanks for your interest.  I made a few suggestions, but haven't explicitly tested them.  Also could you add something to the demo file that includes the added option.

2020-04-23 04:05 UTC, djkramnik commented on src/index.ts
> +export default async (el: HTMLElement, options?: Options | undefined) => {
I don't believe you need the ` | undefined` here, is the use of ? sufficient?

2020-04-23 04:05 UTC, djkramnik commented on src/index.ts
> +  const lines = getLineElements(getLines(el), options?.markup);
```suggestion
  const lines = getLineElements(getLines(el), options ? options.markup : undefined);
```

2020-04-23 04:05 UTC, djkramnik commented on src/utils.ts
> +  markup: string | undefined
```suggestion
  markup?: string
```

2020-04-23 04:05 UTC, djkramnik commented on src/utils.ts
> +      if (markup) {
```suggestion
      if (typeof markup === 'string') {
```

2020-04-23 09:57 UTC, hansds commented on src/index.ts
> +export default async (el: HTMLElement, options?: Options | undefined) => {
@djkramnik I added your suggestions, tested them and approved. I'm quite unexperienced in typescript I'm afraid!

2020-04-23 09:59 UTC, hansds commented
@djkramnik thanks for your suggestions! I added them, and included a demo for the extended usage.

2020-04-30 14:05 UTC, merged

2020-05-04 17:30 UTC, hansds commented
@djkramnik thanks for the accepted PR! Can you publish to npm so I can remove my fork and update my dependencies? Thanks!